License: none
ManifestType: merged
Installers:
- Architecture: x86
  InstallerUrl: https://download.geogebra.org/package/windows-geometry
  InstallerType: exe
  InstallerSha256: 4732193735151BDFC51AFF5DBC1422CE530EDA267427AC4BF02DECC0A435D87B
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
PackageVersion: 1.0.0
DefaultLocale: en-US
PackageLocale: en-US
ManifestVersion: 1.4.0
PackageName: PAKETTEST
Publisher: CN=HS2N
PackageIdentifier: HS2N.PAKETTEST
ShortDescription: testpaket
Copyright: Copyright Â© 2023 International GeoGebra Institute

