ShortDescription: testpaket
Installers:
- InstallerUrl: https://download.geogebra.org/package/windows-geometry
  InstallerSha256: 4732193735151BDFC51AFF5DBC1422CE530EDA267427AC4BF02DECC0A435D87B
  Architecture: x86
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  InstallerType: exe
License: none
Publisher: CN=HS2N
PackageVersion: 1.0.0
Copyright: Copyright Â© 2023 International GeoGebra Institute
ManifestType: merged
DefaultLocale: en-US
PackageLocale: en-US
PackageIdentifier: HS2N.PAKETTEST
PackageName: PAKETTEST
ManifestVersion: 1.4.0

