License: none
Publisher: CN=HS2N
ShortDescription: testpaket
PackageName: PAKETTEST
PackageLocale: en-US
Installers:
- InstallerUrl: https://download.geogebra.org/package/windows-geometry
  Architecture: x86
  InstallerSwitches:
    SilentWithProgress: --silent
    Silent: --silent
  InstallerType: exe
  InstallerSha256: 4732193735151BDFC51AFF5DBC1422CE530EDA267427AC4BF02DECC0A435D87B
PackageVersion: 1.0.0
DefaultLocale: en-US
ManifestType: merged
PackageIdentifier: HS2N.PAKETTEST
ManifestVersion: 1.4.0
Copyright: Copyright Â© 2023 International GeoGebra Institute

