# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: HS2N.PAKETTEST
PackageVersion: 1.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: HS2N.PAKETTEST
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: CN=HS2N
PackageName: PAKETTEST
License: none
Copyright: Copyright Â© 2023 International GeoGebra Institute
ShortDescription: testpaket
ManifestType: defaultLocale
ManifestVersion: 1.4.0
# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: HS2N.PAKETTEST
PackageVersion: 1.0.0
Installers:
- InstallerUrl: https://download.geogebra.org/package/windows-geometry
  Architecture: x86
  InstallerType: exe
  InstallerSha256: 4732193735151BDFC51AFF5DBC1422CE530EDA267427AC4BF02DECC0A435D87B
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
ManifestType: installer
ManifestVersion: 1.4.0



