Copyright: Copyright Â© 2023 International GeoGebra Institute
ManifestType: merged
PackageIdentifier: HS2N.PAKETTEST
PackageLocale: en-US
ShortDescription: testpaket
PackageName: PAKETTEST
Publisher: CN=HS2N
DefaultLocale: en-US
License: none
PackageVersion: 1.0.0
ManifestVersion: 1.4.0
Installers:
- InstallerSwitches:
    SilentWithProgress: --silent
    Silent: --silent
  InstallerSha256: 4732193735151BDFC51AFF5DBC1422CE530EDA267427AC4BF02DECC0A435D87B
  InstallerType: exe
  Architecture: x86
  InstallerUrl: https://download.geogebra.org/package/windows-geometry

