DefaultLocale: en-US
Description: Postman is a collaboration platform for API development. Postman's features simplify each step of building an API and streamline collaboration so you can create better APIs â€” faster.
PrivacyUrl: https://www.postman.com/legal/privacy-policy/
ManifestType: merged
MinimumOSVersion: 10.0.0.0
PackageIdentifier: Postman.Postman
PublisherUrl: https://www.postman.com/
LicenseUrl: https://www.postman.com/legal/eula/
PackageVersion: 10.9.4
PackageLocale: en-US
PackageName: Postman
Copyright: Copyright (c) 2023 Postman, Inc. All rights reserved.
ShortDescription: The Collaboration Platform for API Development
PackageUrl: https://www.postman.com/
License: Proprietary
ManifestVersion: 1.4.0
Moniker: postman
Installers:
- Scope: user
  InstallerSwitches:
    SilentWithProgress: -s
    Silent: -s
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://dl.pstmn.io/download/version/10.9.4/win64
  ProductCode: Postman
  InstallerSha256: F164EED1E7CD289F256A79230A1531321B979DC59385AF7B2A34BA3C6904F5EB
  UpgradeBehavior: install
  InstallerLocale: en-US
Tags:
- api
- postman
- development
CopyrightUrl: https://www.postman.com/legal/eula/
Publisher: Postman
Author: Postman
InstallModes:
- interactive
- silent
- silentWithProgress
PublisherSupportUrl: https://www.postman.com/support/

