# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Postman.Postman
PackageVersion: 9.1.1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Postman.Postman
PackageVersion: 9.1.1
PackageLocale: en-US
Publisher: Postman
PublisherUrl: https://www.postman.com/
PublisherSupportUrl: https://www.postman.com/support/
PrivacyUrl: https://www.postman.com/legal/privacy-policy/
Author: Postman
PackageName: Postman
PackageUrl: https://www.postman.com/
License: Copyright (c) 2021 Postman, Inc. All rights reserved.
LicenseUrl: https://www.postman.com/legal/eula/
Copyright: Copyright (c) 2021 Postman, Inc. All rights reserved.
CopyrightUrl: https://www.postman.com/legal/eula/
ShortDescription: The Collaboration Platform for API Development
Description: Postman is a collaboration platform for API development. Postman's features simplify each step of building an API and streamline collaboration so you can create better APIs â€” faster.
Moniker: postman
Tags:
  - api
  - postman
  - development
ManifestType: defaultLocale
ManifestVersion: 1.0.0
# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Postman.Postman
PackageVersion: 9.1.1
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - InstallerLocale: en-US
    Architecture: x64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://dl.pstmn.io/download/version/9.1.1/win64
    InstallerSha256: 960499c5ae22b66c1e813f5d765fa5ba0841fbb1cfd931c87cfa1e421e0de661
    InstallerSwitches:
      Silent: -s
      SilentWithProgress: -s
    UpgradeBehavior: install
    ProductCode: Postman
  - InstallerLocale: en-US
    Architecture: x86
    InstallerType: exe
    Scope: user
    InstallerUrl: https://dl.pstmn.io/download/version/9.1.1/win32
    InstallerSha256: a6f45197f832134554f1a3ff006892d15820be2654738790a7ab5ff89931e084
    InstallerSwitches:
      Silent: -s
      SilentWithProgress: -s
    UpgradeBehavior: install
    ProductCode: Postman
ManifestType: installer
ManifestVersion: 1.0.0



