Publisher: Zoho Mail
PrivacyUrl: https://www.zoho.com/privacy.html
PackageLocale: en-US
ManifestVersion: 1.1.0
ManifestType: merged
Installers:
- InstallerSha256: 02E170DB3061AA6769100A51F1B2A251306F715130E2F4D157D6378F75F50341
  Architecture: x64
  InstallerUrl: https://downloads.zohocdn.com/zmail-desktop/windows/zoho-mail-desktop-installer-x64-v1.4.1.exe
- InstallerSha256: 8F70144D5ADEF788E420A110CD0B529330319A09CD8134F9902EB1D29B24077E
  Architecture: x86
  InstallerUrl: https://downloads.zohocdn.com/zmail-desktop/windows/zoho-mail-desktop-installer-x86-v1.4.1.exe
UpgradeBehavior: install
PackageName: Zoho Mail - Desktop
PackageIdentifier: Zoho.ZohoMail.Desktop
PublisherUrl: https://www.zoho.com/
License: Proprietary
Tags:
- email
PackageVersion: 1.4.1
PublisherSupportUrl: https://help.zoho.com/portal/en/home
InstallerType: nullsoft
MinimumOSVersion: 10.0.0.0
PackageUrl: https://www.zoho.com/mail/
Copyright: Copyright Â© 2022 Zoho Mail
ShortDescription: The comfort of your webmail now in your desktop with Zoho Mail Desktop

